### ISSUE TITLE
Typescript 2.0, @types/meteor and typings

### ISSUE THREAD

**Issue by jakobrosenberg** [meteor-typings/meteor#24]
After setting VSCode Typescript to 2.0 my Meteor imports no longer works (in VSCODE). VSCode now seems to ignore typings, while npm install --save @types/meteor`` doesn't work.

I don't know if this link offers any explanation.
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by barbatus** [comment]
This is not related, Meteor is not NPM, hence its typings is not contained in NPM.
Anyways, it should work if you have them installed as `typings i env~meteor --global`, and have tsconfig.json in the root that references them.

**Comment by jakobrosenberg** [comment]
I have them install as typings as you described and it works by default. 

But if I follow the instructions below and set VSCode to use Typescript 2.0, VSCode can no longer find any of the previously working global typings.
https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

For what it's worth using Typescript 2.0 in VSCode didn't fix the missing Object.assign, so I've reverted to the included version of Typescript.

**Comment by jakobrosenberg** [comment]
Sorry for the late reply.

I solved the issue by adding "**/*.ts" to the "include" array in ts.config.json
